URL_LOGIN = "/dyn/login.json"
URL_LOGOUT = "/dyn/logout.json"
URL_VALUES = "/dyn/getValues.json"
URL_ALL_VALUES = "/dyn/getAllOnlValues.json"
URL_ALL_PARAMS = "/dyn/getAllParamValues.json"
URL_LOGGER = "/dyn/getLogger.json"
URL_DASH_LOGGER = "/dyn/getDashLogger.json"
URL_DASH_VALUES = "/dyn/getDashValues.json"

ELECTRIC_POTENTIAL = 'electric_potential'
ELECTRIC_CURRENT = 'electric_current'
FREQUENCY = 'frequency'
ENERGY = 'energy'
POWER = 'power'

FIELD_MAPPING = {'6100_40263F00': {'name': 'grid_power',
                                   'description': 'Grid power',
                                   'physical_quantity': 'power',
                                   'unit': 'watt',
                                   'type': 'gauge',
                                   'factor': 1.0},
                 '6100_00465700': {'name': 'frequency',
                                   'description': 'frequency',
                                   'physical_quantity': 'power',
                                   'unit': 'hertz',
                                   'type': 'gauge',
                                   'factor': 100.0},
                 '6100_00464800': {'name': 'voltage_l1',
                                   'description': 'Voltage L1',
                                   'physical_quantity': 'electric_potential',
                                   'unit': 'volt',
                                   'type': 'gauge',
                                   'factor': 100.0},
                 '6100_00464900': {'name': 'voltage_l2',
                                   'description': 'Voltage L2',
                                   'physical_quantity': 'electric_potential',
                                   'unit': 'volt',
                                   'type': 'gauge',
                                   'factor': 100.0},
                 '6100_00464A00': {'name': 'voltage_l3',
                                   'description': 'Voltage L3',
                                   'physical_quantity': 'electric_potential',
                                   'unit': 'volt',
                                   'type': 'gauge',
                                   'factor': 100.0},
                 '6100_40465300': {'name': 'current_l1',
                                   'description': 'Current L1',
                                   'physical_quantity': 'electric_current',
                                   'unit': 'ampere',
                                   'type': 'gauge',
                                   'factor': 1000.0},
                 '6100_40465400': {'name': 'current_l2',
                                   'description': 'Current L2',
                                   'physical_quantity': 'electric_current',
                                   'unit': 'ampere',
                                   'type': 'gauge',
                                   'factor': 1000.0},
                 '6100_40465500': {'name': 'current_l3',
                                   'description': 'Current L3',
                                   'physical_quantity': 'electric_current',
                                   'unit': 'ampere',
                                   'type': 'gauge',
                                   'factor': 1000.0},
                 '6100_0046C200': {'name': 'pv_power',
                                   'description': 'PV power',
                                   'physical_quantity': 'power',
                                   'unit': 'watt',
                                   'type': 'gauge',
                                   'factor': 1.0},
                 '6380_40451F00': {'name': 'pv_voltage',
                                   'description': 'PV voltage (average of all PV channels)',
                                   'physical_quantity': 'electric_potential',
                                   'unit': 'volt',
                                   'type': 'gauge',
                                   'factor': 100.0},
                 '6380_40452100': {'name': 'pv_current',
                                   'description': 'PV current (average of all PV channels)',
                                   'physical_quantity': 'electric_current',
                                   'unit': 'ampere',
                                   'type': 'gauge',
                                   'factor': 1000.0},
                 '6400_0046C300': {'name': 'pv_gen_meter',
                                   'description': 'PV generation meter',
                                   'physical_quantity': 'energy',
                                   'unit': 'kilo_watt_hour',
                                   'type': 'counter',
                                   'factor': 1000.0},
                 '6400_00260100': {'name': 'total_yield',
                                   'description': 'Total yield',
                                   'physical_quantity': 'energy',
                                   'unit': 'kilo_watt_hour',
                                   'type': 'counter',
                                   'factor': 1000.0},
                 '6400_00262200': {'name': 'daily_yield',
                                   'description': 'Daily yield',
                                   'physical_quantity': 'energy',
                                   'unit': 'kilo_watt_hour',
                                   'type': 'counter',
                                   'factor': 1000.0},
                 '6100_40463600': {'name': 'grid_power_supplied',
                                   'description': 'Grid power supplied',
                                   'physical_quantity': 'power',
                                   'unit': 'watt',
                                   'type': 'gauge',
                                   'factor': 1.0},
                 '6100_40463700': {'name': 'grid_power_absorbed',
                                   'description': 'Grid power absorbed',
                                   'physical_quantity': 'power',
                                   'unit': 'watt',
                                   'type': 'gauge',
                                   'factor': 1.0},
                 '6400_00462400': {'name': 'grid_total_yield',
                                   'description': 'Grid total yield',
                                   'physical_quantity': 'energy',
                                   'unit': 'kilo_watt_hour',
                                   'type': 'counter',
                                   'factor': 1000.0},
                 '6400_00462500': {'name': 'grid_total_absorbed',
                                   'description': 'Grid total absorbed',
                                   'physical_quantity': 'energy',
                                   'unit': 'kilo_watt_hour',
                                   'type': 'counter',
                                   'factor': 1000.0},
                 '6100_00543100': {'name': 'current_consumption',
                                   'description': 'Current consumption',
                                   'physical_quantity': 'power',
                                   'unit': 'watt',
                                   'type': 'gauge',
                                   'factor': 1.0},
                 '6400_00543A00': {'name': 'total_consumption',
                                   'description': 'Total consumption',
                                   'physical_quantity': 'energy',
                                   'unit': 'kilo_watt_hour',
                                   'type': 'counter',
                                   'factor': 1000.0}}